[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tomerpeckage"
version = "0.1.0"
description = "A custom library for Google Colab"
authors = [
    {name = "User"}
]
dependencies = []

[tool.setuptools]
packages = ["tomerpeckage"]
